### ISSUE TITLE
Separation and width strings overlap

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#418]
**Test device**
Dell Laptop
**Operating System**
Win 10
**Browser**
chrome
**Problem description**
For https://github.com/phetsims/QA/issues/389
Not an issue in the published version of the sim.  The slit width and slit separation strings overlap with the box with the measurements in them.
**Steps to reproduce**
1. Use string Test double and look at the slits screen
2. Applies to water, sound, and light

**Visuals**
![overlapstrings](https://user-images.githubusercontent.com/41024075/62252856-446ba780-b3b1-11e9-8434-1a5e59f4dfea.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Wave Interference‬:‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/2.0.0-dev.7/phet/wave-interference_en_phet.html?stringTest=double
Version: 2.0.0-dev.7 2019-07-30 22:17:13 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
Proposed fix committed, @KatieWoe can you please review on phettest?  Close if all is well.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by KatieWoe** [comment]
Actually, I see that it still happens with string test long in master (along with other similar slider strings, such as those on the 4th screen.)

**Comment by samreid** [comment]
Here's a snapshot of that problem:

![image](https://user-images.githubusercontent.com/679486/62548315-d5180c80-b823-11e9-874b-68a9a6a67c02.png)

It appears those sliders aren't as wide, so the `maxWidth` overflows a bit.

**Comment by samreid** [comment]
Proposed fix committed, @KatieWoe can you please review and test on master?  Close if all is well.

**Comment by KatieWoe** [comment]
Few instances still
![stillhere](https://user-images.githubusercontent.com/41024075/62549898-861fa680-b826-11e9-8b06-4a43a1c804b4.png)
![stillheretwo](https://user-images.githubusercontent.com/41024075/62549899-861fa680-b826-11e9-91f5-24271c59c117.png)

**Comment by samreid** [comment]
@KatieWoe thanks for your persistence on this issue, it led me to the realization that https://github.com/phetsims/wave-interference/issues/420 is actually changing the widths of the number controls, which is, in turn, causing more overlap in the text.  I'll pursue a fix for https://github.com/phetsims/wave-interference/issues/420 then return to this issue.

**Comment by samreid** [comment]
I pushed a fix for #420 and the arrow buttons are no longer a function of the string length.  Now I'll tune the maxWidth values.

**Comment by samreid** [comment]
One more comment before I commit.  With longer-than-english strings, the heights of boxes are different and the vertical alignment can be off by a little bit:

![image](https://user-images.githubusercontent.com/679486/62555809-d4d23e00-b830-11e9-9543-c4190231d216.png)

Perhaps this warrants a separate issue?

**Comment by samreid** [comment]
OK I adjusted the `maxWidth` after the NumberControl.arrowButton sizes were fixed.  @KatieWoe will you please re-test?  Also, we should keep in mind if we change the tweaker button sizes again, we will need to readjust these `maxWidth`s again.

**Comment by KatieWoe** [comment]
Looks solid from what I can see on master.  I did notice that the distance between them is different for each slider, and some get closer than others, but I don't think any overlap.

**Comment by samreid** [comment]
Thanks, closing for now!
